FROM python:3.11

WORKDIR /app

RUN pip install -U pip wheel setuptools
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]